### ISSUE TITLE
option notebook

### ISSUE THREAD

**Issue by revesansparole** [revesansparole/pkglts#22]
pmg rg notebook does not copy images along created rst

**Comment by artzet-s** [comment]
Hi, 
Indeed  images is not copy along created rst with the directive "%matplotlib inline", 
I had only tested with the directive "%matplotlib notebook" which works well.

However, I fix the bug with the directive "%matplotlib inline" and push a new version in a pull requests.

**Comment by revesansparole** [comment]
fixed by SImon
