### ISSUE TITLE
AttributeError when upgrading from older version

### ISSUE THREAD

**Issue by jldinh** [revesansparole/pkglts#24]
Running pmg init, add or regenerate throws the following error.

```
  File "[some path]/pkglts/src/pkglts/option/pysetup/handlers.py", line 29, in pkg_url
    url = env.globals['base'].url
AttributeError: 'ConfigSection' object has no attribute 'url'
```

**Comment by revesansparole** [comment]
You must have created your package with an "old" version of pkglts. I started handling versions of config file only recently. If you send me your pkg_cfg.json file I'll upgrade it.

**Comment by jldinh** [comment]
OK thanks, I checked pkg_cfg.json and I think I will be able to figure it out.
I made a [commit on my fork to ignore the error](https://github.com/jldinh/pkglts/commit/291ef85c1652e730a858fb627bf4892c1d918c5d), but I guess it might be better to actually edit the json file instead.

However, I then ran into another issue when trying to regenerate:

```
2016-07-21 13:10:49,910 INFO (pkglts.manage_script): regenerate package
Traceback (most recent call last):
  File "/home/jl/Library/Python/2.7/bin/pmg", line 9, in <module>
    load_entry_point('pkglts==1.1.0', 'console_scripts', 'pmg')()
  File "[path]/pkglts/src/pkglts/manage_script.py", line 139, in main
    action[args.action](*args.action_args, **extra)
  File "[path]/pkglts/src/pkglts/manage_script.py", line 57, in action_regenerate
    regenerate_package(env, overwrite=overwrite)
  File "[path]/pkglts/src/pkglts/manage.py", line 162, in regenerate_package
    if exists(pth) and modified_file_hash(pth, hm_ref):
  File "[path]/pkglts/src/pkglts/hash_management.py", line 88, in modified_file_hash
    raise IOError("%s not under check" % key)
IOError: .pypirc not under check
```

Looks like a change tracker has been added since the last version I used. Is it related at all?

**Comment by revesansparole** [comment]
Actually there has been a major change recently which I pushed silently since I thought I knew all the users of pkglts. You unfortunately went under the radar. Any chance I can access the code of your package to make the necessary changes?

Since then I put some mechanism in place to better handle version so it's hopefully a one time shot.

**Comment by jldinh** [comment]
I have not uploaded the package yet, as I wanted to pick a license and set up author details first.
But don't worry, I have not actually edited the pkglts config at all yet, so I will just create a new folder.
I can let you know once I have uploaded it, if you want.

**Comment by revesansparole** [comment]
Don't forget to pull the latest version of pkglts from github. And don't
hesitate to ask me back if you need some help. I have upgraded the
documentation online but I'm not sure it's comprehensive enough.

Cheers,

Jerome

http://revesansparole.wordpress.com

**Comment by jldinh** [comment]
OK thanks for your help. I uploaded my unfinished project: https://github.com/jldinh/multicell
I did notice another issue but I will open a separate issue. Feel free to close this one.
