### ISSUE TITLE
pysetup option does not work in the latest version on pypi

### ISSUE THREAD

**Issue by jldinh** [revesansparole/pkglts#25]
It might be configuration-specific, as I think the same version works fine on my other computer, but I will need to check.

When using `pmg rg`, I get the error message:

```
  File "C:\Python27\Lib\site-packages\pkglts\option\pysetup\handlers.py", line 69, in environment_extensions
    for tup in env.globals['pysetup'].require:
AttributeError: 'ConfigSection' object has no attribute 'require'
```

**Comment by jldinh** [comment]
The version from github works on the computer that has the issue with the pypi version. So I think it's just pypi that needs to be updated.

**Comment by revesansparole** [comment]
I can't chekc it just now. I'll do it on friday.

Thanks,

Jerome

http://revesansparole.wordpress.com

**Comment by revesansparole** [comment]
I did a quick check and haven't seen anything unusual with pypi option.
It's working for my packages.

Will have to dig a bit more when i come back in a month. If it's blocking
for you can you try to remove the pypi option from your package inthe
meantime?

Sorry about that

Jerome

http://revesansparole.wordpress.com

**Comment by pradal** [comment]
I have the same problem.

The last version on PyPi have been uploaded on 2016-07-12, while the bug on pysetup (https://github.com/revesansparole/pkglts/commit/7fded4d73791843f362c702adbb47d5a861a8e8e) have been fixed on 2016-07-13.

Please, just upload the latest version to PyPi, and close the issue.
