### ISSUE TITLE
Bug in the management of namespaces

### ISSUE THREAD

**Issue by pradal** [revesansparole/pkglts#28]
In base, when namespace is set, the namespace_packages keyword is not set in the setup.py

**Comment by revesansparole** [comment]
You are right. However packages with namespace seems to work fine even without this keyword, strange?

To correct this omission I went to this page:
https://packaging.python.org/namespace_packages/

They recommand to use 'pkgutil' approach instead of 'pkg_resources' which also does not require change in setup.py.

Any thought?

**Comment by pradal** [comment]
Without declaring namespace packages, this works fnie for packages in
isolation. But, if you have multiple packages, this creates problems.

I was using a trick (try: ... except: ...). But things have changed
through time. I will investigate.

Best

**Comment by revesansparole** [comment]
I just tested it with two separate packages and the same namespace and it worked fine.

Point is I will correct it but I was more incline to use the 'pkgutil' method which is more compatible with both pyhton 2 and 3. Unless you have arguments against it.

**Comment by christian34** [comment]
As far as I understand from the page you referenced, an important recommendation is to use in every packages that share the same namespace the same method. In case a convention has already be chosen, it would therefore be good to be able to let user choose. Why not offering the 'new' recommended method as default and add an option for generating 'old style / compatible' setup / layout ?

**Comment by pradal** [comment]
Rational: There are 3 ways to define a new package (see https://packaging.python.org/namespace_packages/)
1. Omit __init__.py: This solution, which is only available on Python 3.3, is equivalent to the one I have built in deploy (create_namespace). This method will manage every package in the namespace in the same way.
2. pkg_util
3. pkg_resources (setuptools): This is the method we use in openalea. The point is that method is no more recommended for distribution of new namespace, but 
    

> it’s recommended to continue using this as the different methods are not cross-compatible and  
    it’s not advisable to try to migrate an existing package.

So, for existing packages, the strategy used in openalea (pkg_resources then pkg_util) is the only one that will be cross-compatible with the existing packages
