### ISSUE TITLE
Regenerate command fail for old packages

### ISSUE THREAD

**Issue by pradal** [revesansparole/pkglts#41]
Clone the package https://github.com/revesansparole/VersionClimber_test1
Run the command:
pmg rg

The command fail while nothing has changed.
Error stack:
>   File "/Users/pradal/miniconda2/envs/vclimber/lib/python2.7/site-packages/pkglts/manage.py", line 160, in regenerate_package
>     if exists(pth) and modified_file_hash(pth, hm_ref):
>   File "/Users/pradal/miniconda2/envs/vclimber/lib/python2.7/site-packages/pkglts/hash_management.py", line 88, in modified_file_hash
>     raise IOError("%s not under check" % key)
> IOError: doc/index.rst not under check

**Comment by revesansparole** [comment]
This test package was under a really old version of pkglts before I started maintaining upward compatibility. Everything must be sorted now :)
